---

port: 4080
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [
    CNAME, README.md, .gitignore, vendor, gulpfile.js, node_modules,
    package.json, nbproject, Gemfile
]
permalink: /:title ## disables post output
timezone: PST
lsi: false
markdown: kramdown

kramdown:
  auto_ids:         true
  input:            GFM
  hard_wrap:        false
#  footnote_nr:    1
#  entity_output:  as_char
#  toc_levels:     1..6
#  smart_quotes:   lsquo,rsquo,ldquo,rdquo


### content configuration ###
title:       "Testify - Java Testing Made Simple"
keywords:    "testify-project, Testify, Java, Mockito, Annotations, JSR-330, Docker, JUnit, TestNG, Spring, SpringBoot, HK2, Jersey, JAX-RS, Google Guice, gRPC"
description: "A landing page for Testify Project, a Java Testing Framework that provides a common set of annotations for writing effective unit, integration and system tests."
source_link: "https://github.com/testify-project/testify"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: "UA-96183432-1"

### Collections ###
collections:
  docs:
    output: true

doc_versions: []

### Project Variables ###
### For GitHub Metadata see: https://help.github.com/articles/repository-metadata-on-github-pages/
repository:                 "testify-project/testify"
testify_version:            "1.0.5"
resources_version:          "1.0.3"
virtual_resources_version:  "1.0.3"
examples_version:           "1.0.0"
spring_version:             "5.0.2.RELEASE"
springbood_version:         "1.5.9.RELEASE"
jersey_version:             "2.26"
hk2_version:                "2.5.0-b42"
guice_version:              "4.1.0"
grpc_version:               "1.7.0"
junit4_version:              "4.12"
junit5_version:              "5.2.0"
mockito_version:            "2.11.0"
assertj_version:            "3.8.0"
java_version:               "1.8"
jdk_version:                "8"
git_version:                "2.9.3"
maven_version:              "3.1.1"
docker_version:             "1.11.2 - 17.05.0~ce"
inject_version:             "1"

### Template Colors ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  fnavy:     '#3c4e5c'
  forange:   '#e4844a'
  fyellow:   '#bb9236'
  fblue:     '#a3b4a4'
  fblack:    '#130c1e'
  fbrown:    '#765e51'
